#include "logo.h" // The file generated by our python script

typedef unsigned char uint8_t;
typedef unsigned short uint16_t;

// VGA Graphics Mode 13h memory starts at 0xA0000
uint8_t* vga_graphics_buffer = (uint8_t*)0xA0000;

// Hardware Port I/O
static inline void port_byte_out(uint16_t port, uint8_t data) {
    __asm__("out %%al, %%dx" : : "a" (data), "d" (port));
}

// Load the OrionOS Custom Color Palette to the VGA DAC
void load_custom_palette() {
    port_byte_out(0x3C8, 0); 
    for (int i = 0; i < 768; i++) {
        port_byte_out(0x3C9, logo_palette[i]);
    }
    
    // Custom UI Colors
    port_byte_out(0x3C8, 255); // Pure White (for Start Button)
    port_byte_out(0x3C9, 63); port_byte_out(0x3C9, 63); port_byte_out(0x3C9, 63);

    port_byte_out(0x3C8, 254); // Dark Gray/Blue (for Taskbar)
    port_byte_out(0x3C9, 5); port_byte_out(0x3C9, 5); port_byte_out(0x3C9, 15);
}

// Draw a single pixel on the screen
void draw_pixel(int x, int y, uint8_t color) {
    if (x >= 0 && x < 320 && y >= 0 && y < 200) {
        vga_graphics_buffer[(y * 320) + x] = color;
    }
}

// Draw a solid rectangle
void draw_rect(int x, int y, int width, int height, uint8_t color) {
    for (int i = 0; i < height; i++) {
        for (int j = 0; j < width; j++) {
            draw_pixel(x + j, y + i, color);
        }
    }
}

// Draw the generated OrionOS Logo
void draw_logo(int start_x, int start_y) {
    for (int y = 0; y < 120; y++) {
        for (int x = 0; x < 120; x++) {
            uint8_t color_index = logo_pixels[(y * 120) + x];
            draw_pixel(start_x + x, start_y + y, color_index);
        }
    }
}

extern "C" void kernel_main() {
    // 1. Overwrite standard VGA colors with our custom logo colors
    load_custom_palette();

    // 2. Draw Desktop Background (Index 0 is usually the darkest palette color)
    draw_rect(0, 0, 320, 200, 0);

    // 3. Draw the Logo centered (Screen: 320x200, Logo: 120x120)
    draw_logo(100, 30);

    // 4. Draw Taskbar at the bottom (using custom color 254)
    draw_rect(0, 180, 320, 20, 254);

    // 5. Draw a "Start Button" on the taskbar (using custom color 255)
    draw_rect(2, 182, 30, 16, 255);

    // OS IDLE LOOP
    while (true) {
        // Future keyboard/mouse checks will go here
    }
}
